/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Urbase;

import DB.db_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Amine
 */
public class Cession extends javax.swing.JFrame {

    /**
     * Creates new form Cession
     */
     int kl =1;
   
    ResultSet rs;
    db_connection db;
  //  DefaultTableModel model=new DefaultTableModel();
   //  DefaultTableModel model1=new DefaultTableModel();
     DefaultTableModel model;
     DefaultTableModel model1;
     String id;
      DefaultTableModel model22 ;
     int ajout =0;
     String id_lot;
    public Cession() throws SQLException {
        initComponents();
        db = new db_connection();
        txtref.setFormats("dd-MM-yyyy");
        txtdes3.setVisible(false);
         comboZone.setVisible(false);
        //textZone.setEnabled(false);
        nonEnable();
        table();
        model22 =new DefaultTableModel();
model22.addColumn("id_lot");   
    }
    void nonEnable(){
    txtid.setEnabled(false);
            txtref.setEnabled(false);
             txtref.setEnabled(false);
              txtdes3.setEnabled(false);
            textZone.setEnabled(false);
            
}
    void Enable(){
    txtid.setEnabled(true);
            txtref.setEnabled(true);
             txtref.setEnabled(true);
              txtdes3.setEnabled(true);
            
            
}
    
    
    
    public void table() throws SQLException {
       // String t[] = {"id","code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
    //rs = db.exécutionQuery("select id_lot , cod_lot,lib_lot, sup_lot, state_lot from lot");
     rs = db.exécutionQuery("select id_cession,lib_lot,n_acte,date_acte,date_attribution from cession left join  lot on  cession.id_lot=lot.id_lot where type=1 and cession.id_lot='"+Lot.id+"'");

         model=new DefaultTableModel();
    model1=new DefaultTableModel();
 
    model.addColumn("lib_lot");
model.addColumn("n_acte");
model.addColumn("date_acte");
//model.addColumn("date_attribution");
 
model.addColumn("id");
       // x = new String[rs.];
       boolean bool=false;
     int xx=0;  
     //new String(gg).equals(EE);
     String EE=Lot.name;
     String gg;
     int ff;
     ff=0;
   while(rs.next()){
model.addRow(new Object[]{rs.getString("lib_lot"),rs.getString("n_acte"),
    rs.getDate("date_acte"),rs.getString("id_cession")});
//model1.addRow(new Object[]{rs.getString("id_cession")});
gg=rs.getString("lib_lot");
if (gg==null){
    System.out.println("Urbase.Cession.table()");
xx++;
}
else{
if(new String(gg).equals(EE)) {
    bool =true; 
    ff=xx;
}
else
    xx++;
}
//model1.addRow(new Object[]{rs.getString("id_lot")});
}
   
 //   x = new String[rs.;
       tbl_prod.setModel(model);
   tbl_prod.getColumnModel().getColumn(3).setMinWidth(0);
   tbl_prod.getColumnModel().getColumn(3).setMaxWidth(0);
   tbl_prod.getColumnModel().getColumn(3).setWidth(0);
      // tbl_prod.setModel(new ResultSetTableModel(rs));
        
        //  TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbl_prod.getModel());
             //  tbl_prod.setRowSorter(sorter);
         //      if(bool==true)
 //tbl_prod.setRowSelectionInterval(ff,ff);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_prod = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtref = new org.jdesktop.swingx.JXDatePicker();
        txtdes3 = new org.jdesktop.swingx.JXDatePicker();
        textZone = new javax.swing.JTextField();
        comboZone = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tbl_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_prod);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setText("num acte");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 60, 100, 27);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel10.setText("date acte :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 100, 100, 27);
        jPanel2.add(txtid);
        txtid.setBounds(120, 60, 100, 30);
        jPanel2.add(txtref);
        txtref.setBounds(120, 100, 190, 30);
        jPanel2.add(txtdes3);
        txtdes3.setBounds(120, 150, 190, 30);
        jPanel2.add(textZone);
        textZone.setBounds(120, 20, 100, 30);

        comboZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboZoneActionPerformed(evt);
            }
        });
        jPanel2.add(comboZone);
        comboZone.setBounds(120, 10, 100, 40);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel9.setText("nom Lot :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 20, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/modifier.png"))); // NOI18N
        jButton3.setText("modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/ajouter.png"))); // NOI18N
        jButton2.setText("ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/supprimer.png"))); // NOI18N
        jButton4.setText("supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/actualiser .png"))); // NOI18N
        jButton9.setText("actualiser");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_prodMouseClicked
textZone.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(),0)));

        txtid.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 1)));
        txtref.setDate((Date)tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 2));
     //   txtdes3.setDate((Date)tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 3));
        id= String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 3));
        //txtran.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 3)));
        // txtid.setEnabled(false);            // TODO add your handling code here:
    }//GEN-LAST:event_tbl_prodMouseClicked
 void  actualiser(){
 txtid.setText("");
 textZone.setText("");

 
 
 
 }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         try {
             rs = db.exécutionUpdate("delete from  cession where id_cession ='"+id+"'");
             table();} catch (SQLException ex) {
             Logger.getLogger(Cession.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(ajout==0){
    ajout=1;
   // actualiser();
    Enable();
}else{
        
            ajout=0;
            nonEnable();
        try {
             Date date=txtref.getDate();
             //Date date2=txtdes3.getDate();
             String newstring = new SimpleDateFormat("yyyy-MM-dd").format(date);
            // String newstring2 = new SimpleDateFormat("yyyy-MM-dd").format(date2);
             
             rs = db.exécutionUpdate("update  cession set n_acte='" +txtid.getText()+"',date_acte= '"+newstring+"'where id_cession='"+id+"'");
             table();
         } catch (SQLException ex) {
             Logger.getLogger(Cession.class.getName()).log(Level.SEVERE, null, ex);
         }}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

              if(ajout==0){
    textZone.setVisible(false);
    comboZone.setVisible(true);
    actualiser();
    Enable();
    String name_Zone;
     ResultSet rs1 ;
     String type="0";
        rs1 = db.exécutionQuery("SELECT lib_lot,lot.id_lot FROM lot left join cession on lot.id_lot=cession.id_lot where cession.id_lot is null");
   
 
        try {
        while (rs1.next()) {
            name_Zone = rs1.getString("lib_lot");
            comboZone.addItem(name_Zone);
          model22.addRow(new Object[]{rs1.getString("id_lot")});
        }
       
          
    } catch (SQLException ex) {
        Logger.getLogger(Permet_Lot.class.getName()).log(Level.SEVERE, null, ex);
    }
ajout=1;
              }else{
        try {
            textZone.setVisible(true);
    comboZone.setVisible(false);
            ajout =0;
             Date date=txtref.getDate();
            // Date date2=txtdes3.getDate();
             String newstring = new SimpleDateFormat("yyyy-MM-dd").format(date);
            // String newstring2 = new SimpleDateFormat("yyyy-MM-dd").format(date2);
                id_lot= String.valueOf(model22.getValueAt(comboZone.getSelectedIndex(), 0));
                String type="1";
             rs = db.exécutionUpdate("INSERT INTO cession (n_acte,date_acte,id_lot,type)VALUES ('"+txtid.getText()+"','"+newstring+"','"+id_lot+"','"+type+"')");
             table();
             actualiser();
             nonEnable();
         } catch (SQLException ex) {
             Logger.getLogger(Cession.class.getName()).log(Level.SEVERE, null, ex);
         }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        txtid.setText("");
        txtref.setDate(null);
        //  txid.setText("");
        txtdes3.setDate(null);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
Lot.kk=1;        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void comboZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboZoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboZoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Cession().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Cession.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboZone;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_prod;
    private javax.swing.JTextField textZone;
    private org.jdesktop.swingx.JXDatePicker txtdes3;
    private javax.swing.JTextField txtid;
    private org.jdesktop.swingx.JXDatePicker txtref;
    // End of variables declaration//GEN-END:variables
}
