/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Urbase;

import DB.db_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Amine
 */
public class Consession extends javax.swing.JFrame {

    /**
     * Creates new form Consession
     */
     int kl =1;
     
    ResultSet rs;
    db_connection db;
  //  DefaultTableModel model=new DefaultTableModel();
   //  DefaultTableModel model1=new DefaultTableModel();
     DefaultTableModel model;
     DefaultTableModel model1;
     String id;
      DefaultTableModel model22 ;
       int ajout =0;
       String id_lot;
    public Consession() throws SQLException {
        
        initComponents();
        db = new db_connection();
        dt1.setFormats("dd-MM-yyyy");
                dt2.setFormats("dd-MM-yyyy");
         comboZone.setVisible(false);
        textZone.setEnabled(false);
        table();
        model22 =new DefaultTableModel();
model22.addColumn("id_lot");   
    }

    public void table() throws SQLException {
       // String t[] = {"id","code_produit","reference","deseignation","rangement","fournisseur","remise","prix","stock"};
    //rs = db.exécutionQuery("select id_lot , cod_lot,lib_lot, sup_lot, state_lot from lot");
     rs = db.exécutionQuery("select id_cession,date_remise,date_resolution ,lib_lot from cession left join  lot on cession.id_lot=lot.id_lot where type=0 and cession.id_lot='"+Lot.id+"'");

         model=new DefaultTableModel();
 //   model1=new DefaultTableModel();
 
    model.addColumn("lib_lot");
model.addColumn("date_remise");
model.addColumn("date_resolution");
 
model.addColumn("id");
       // x = new String[rs.];
       boolean bool=false;
     int xx=0;  
     //new String(gg).equals(EE);
     String EE=Lot.name;
     String gg;
     int ff;
     ff=0;
   while(rs.next()){
model.addRow(new Object[]{rs.getString("lib_lot"),rs.getDate("date_remise"),
    rs.getDate("date_resolution"),rs.getString("id_cession")});
//model1.addRow(new Object[]{rs.getString("id_cession")});
gg=rs.getString("lib_lot");
if (gg==null){
    System.out.println("Urbase.Cession.table()");
xx++;
}
else{
if(new String(gg).equals(EE)) {
    bool =true; 
    ff=xx;
}
else
    xx++;
}
//model1.addRow(new Object[]{rs.getString("id_lot")});
}
   
 //   x = new String[rs.;
       tbl_prod.setModel(model);
   
      // tbl_prod.setModel(new ResultSetTableModel(rs));
        
         // TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbl_prod.getModel());
           //    tbl_prod.setRowSorter(sorter);
          //     if(bool==true)
 //tbl_prod.setRowSelectionInterval(ff,ff);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_prod = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dt2 = new org.jdesktop.swingx.JXDatePicker();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        dt1 = new org.jdesktop.swingx.JXDatePicker();
        textZone = new javax.swing.JTextField();
        comboZone = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tbl_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_prod);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setText("Date remise :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 60, 100, 27);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel10.setText("Date resolution :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 120, 100, 27);
        jPanel2.add(dt2);
        dt2.setBounds(120, 120, 190, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(550, 210, 121, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(360, 210, 127, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(170, 210, 107, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(0, 210, 102, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setText("ajouter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(0, 210, 102, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton7.setText("modifier");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(170, 210, 107, 40);

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton8.setText("supprimer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(360, 210, 127, 40);

        jButton9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton9.setText("actualiser");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(550, 210, 121, 40);
        jPanel2.add(dt1);
        dt1.setBounds(120, 60, 190, 30);
        jPanel2.add(textZone);
        textZone.setBounds(160, 20, 100, 30);

        jPanel2.add(comboZone);
        comboZone.setBounds(130, 20, 130, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel8.setText("nom Lot :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 20, 100, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_prodMouseClicked
textZone.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(),0)));
        Date date ;
      dt1.setDate((Date) tbl_prod.getValueAt(tbl_prod.getSelectedRow(),1));
        
       dt2.setDate((Date)tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 2));
        id= String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 3));        //txtran.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 3)));
        // txtid.setEnabled(false);            // TODO add your handling code here:
    }//GEN-LAST:event_tbl_prodMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        rs = db.exécutionUpdate("delete from cession where id_cession='"+id+"'");
         try {
             table();
         } catch (SQLException ex) {
             Logger.getLogger(Consession.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Date date=dt1.getDate();
             Date date2=dt2.getDate();
             String newstring = new SimpleDateFormat("yyyy-MM-dd").format(date);
             String newstring2 = new SimpleDateFormat("yyyy-MM-dd").format(date2);        // txid.setText(String.valueOf(model1.getValueAt(tbl_prod.getSelectedRow(), 0)));

        rs = db.exécutionUpdate("update  concession set date_remise='" +newstring+"',date_resolution= '"+newstring+"'where id_consession='"+id+"'");
         try {
             table();//afficher et actualiser le tableau
         } catch (SQLException ex) {
             Logger.getLogger(Consession.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(ajout==0){
    textZone.setVisible(false);
    comboZone.setVisible(true);
    String name_Zone;
     ResultSet rs1 ;
        rs1 = db.exécutionQuery("SELECT lib_lot,lot.id_lot FROM lot left join cession on lot.id_lot=cession.id_lot where cession.id_lot is null");
   
 
        try {
        while (rs1.next()) {
            name_Zone = rs1.getString("lib_lot");
            comboZone.addItem(name_Zone);
          model22.addRow(new Object[]{rs1.getString("id_lot")});
        }
       
          
    } catch (SQLException ex) {
        Logger.getLogger(Permet_Lot.class.getName()).log(Level.SEVERE, null, ex);
    }
ajout=1;
        }else{      
        
        Date date=dt1.getDate();
             Date date2=dt2.getDate();
             String newstring = new SimpleDateFormat("yyyy-MM-dd").format(date);
             String newstring2 = new SimpleDateFormat("yyyy-MM-dd").format(date2);
             id_lot= String.valueOf(model22.getValueAt(comboZone.getSelectedIndex(), 0));
             String type="0";
        rs = db.exécutionUpdate("INSERT INTO cession (date_remise,date_resolution,id_lot,type)VALUES ('"+newstring+"','"+newstring2+"','"+id_lot+"','"+type+"')");
         try {
             table();
             //  actualiser();
         } catch (SQLException ex) {
             Logger.getLogger(Consession.class.getName()).log(Level.SEVERE, null, ex);
         }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        //rs = db.exécutionUpdate("INSERT INTO investisseur (cod_invst,nom_invst,activite)VALUES ('"+txtid.getText()+"','"+txtref.getText()+"','"+txtdes2.getText()+"')");
        //    table();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // txid.setText(String.valueOf(model1.getValueAt(tbl_prod.getSelectedRow(), 0)));

      //  rs = db.exécutionUpdate("update  investisseur set cod_invst='" +txtid.getText()+"',nom_invst= '"+txtref.getText()+"'where id_invst='"+id+"'");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      //  rs = db.exécutionUpdate("delete from  investisseur where id_invst='"+id+"'");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
Lot.kk=1;        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Consession().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Consession.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboZone;
    private org.jdesktop.swingx.JXDatePicker dt1;
    private org.jdesktop.swingx.JXDatePicker dt2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_prod;
    private javax.swing.JTextField textZone;
    // End of variables declaration//GEN-END:variables
}
