/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Urbase;

import DB.db_connection;
import static DB.db_connection.IPHOST;
import static com.lowagie.text.pdf.PdfFileSpecification.url;
import static com.lowagie.text.pdf.PdfName.AA;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Amine
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
          this.setLocationRelativeTo(null);  // *** this will center your app ***
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu10.setText("Edit");
        jMenuBar3.add(jMenu10);

        jMenu2.setText("File");
        jMenuBar4.add(jMenu2);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar5.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar5.add(jMenu8);

        jMenu12.setText("File");
        jMenuBar6.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar6.add(jMenu13);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Service info\\Desktop\\RZZ.jpg")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAutoscrolls(true);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(700, 32769));

        jMenu11.setText("Fichiers ");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem5.setText("Zone");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem6.setText("Lot");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem7.setText("Investisseur");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem7);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem11.setText("Outils");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem11);

        jMenuBar1.add(jMenu11);

        jMenu14.setText("Recherche  ");
        jMenu14.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenu14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu14MouseClicked(evt);
            }
        });
        jMenu14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu14ActionPerformed(evt);
            }
        });

        jMenuItem14.setText("Par Wilaya");
        jMenu14.add(jMenuItem14);

        jMenuItem15.setText("Par Zone");
        jMenu14.add(jMenuItem15);

        jMenuItem16.setText("Par Investisseur");
        jMenu14.add(jMenuItem16);

        jMenuItem17.setText("Par Activité");
        jMenu14.add(jMenuItem17);

        jMenuItem18.setText("Général");
        jMenu14.add(jMenuItem18);

        jMenuBar1.add(jMenu14);

        jMenu4.setText("Etat d'impression   ");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/Search-icon.png"))); // NOI18N
        jMenuItem10.setText("Detail Zone");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem2.setText("Zone");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Lot");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem8.setText("Investisseur");
        jMenu4.add(jMenuItem8);

        jMenu15.setText("Statistiques");

        jMenuItem13.setText("Zones");
        jMenuItem13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem13MouseClicked(evt);
            }
        });
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem13);

        jMenuItem9.setText("Investisseur");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem9);

        jMenuItem12.setText("Lots");
        jMenuItem12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem12MouseClicked(evt);
            }
        });
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem12);

        jMenu4.add(jMenu15);

        jMenuBar1.add(jMenu4);

        jMenu16.setText("Autre");
        jMenu16.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem4.setText("Wilaya");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem4);

        jMenuBar1.add(jMenu16);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {    
            
            String myreport = "C:\\Users\\admin\\Desktop\\projet2\\Projet312017\\Urbase2\\Urbase2\\src\\edition\\Global.jrxml";
            JasperReport  jasperReport ;
            
            
            jasperReport = JasperCompileManager.compileReport(myreport);
            //System.out.println("rrrrrrr");
            db_connection db;
             db = new db_connection();
             
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null ,db.connection );
            //  System.out.println("sssss");
            JasperViewer.viewReport(jasperPrint,false);
         //   int DISPOSE_ON_CLOSE1 = JasperViewer.DISPOSE_ON_CLOSE
                 
            
        } catch (JRException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            System.out.println("thaankyou");
        }
       
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
 try {    
            
            String myreport = "C:\\Users\\Amine\\Desktop\\projet2\\Projet312017\\Urbase2\\Urbase2\\src\\Urbase\\report1.jrxml";
            JasperReport  jasperReport ;
            
            Map parametersMap = new HashMap();  
            parametersMap.put("test3",1);
            jasperReport = JasperCompileManager.compileReport(myreport);
            //System.out.println("rrrrrrr");
            db_connection db;
             db = new db_connection();
             String a ="";
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parametersMap ,db.connection );
            //  System.out.println("sssss");
            
            
            
            
            JasperViewer.viewReport(jasperPrint,false);
         //   int DISPOSE_ON_CLOSE1 = JasperViewer.DISPOSE_ON_CLOSE
                 
            
        } catch (JRException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            System.out.println("thaankyou");
        } 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            Wilaya wilaya =new Wilaya();
            wilaya.setVisible(true); 
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            Zone_Indst zone= new Zone_Indst();
            zone.setVisible(true);// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            Lot lot =new Lot();
            lot.setVisible(true);// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            Invst inv =new Invst();
            inv.setVisible(true);// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
     try {    
            
            String myreport = "C:\\Users\\Amine\\Desktop\\projet2\\Projet312017\\Urbase2\\Urbase2\\src\\Urbase\\LOT_Pris.jrxml";
            JasperReport  jasperReport ;
            
            Map parametersMap = new HashMap();  
            parametersMap.put("test3",1);
            jasperReport = JasperCompileManager.compileReport(myreport);
            //System.out.println("rrrrrrr");
            db_connection db;
             db = new db_connection();
             String a ="";
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,null ,db.connection );
            //  System.out.println("sssss");
            
            
            
            
            JasperViewer.viewReport(jasperPrint,false);
         //   int DISPOSE_ON_CLOSE1 = JasperViewer.DISPOSE_ON_CLOSE
                 
            
        } catch (JRException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            System.out.println("thaankyou");
        }         // TODO ad   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem13MouseClicked
try {    
            
            String myreport = "C:\\Users\\admin\\Desktop\\projet2\\Projet312017\\Urbase2\\Urbase2\\src\\Urbase\\LOT_Pris.jrxml";
            JasperReport  jasperReport ;
            
            Map parametersMap = new HashMap();  
            parametersMap.put("test3",1);
            jasperReport = JasperCompileManager.compileReport(myreport);
            //System.out.println("rrrrrrr");
            db_connection db;
             db = new db_connection();
             String a ="";
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parametersMap ,db.connection );
            //  System.out.println("sssss");
            
            
            
            
            JasperViewer.viewReport(jasperPrint,false);
         //   int DISPOSE_ON_CLOSE1 = JasperViewer.DISPOSE_ON_CLOSE
                 
            
        } catch (JRException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            System.out.println("thaankyou");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13MouseClicked

    private void jMenuItem12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem12MouseClicked
 try {    
            
            String myreport = "C:\\Users\\admin\\Desktop\\projet2\\Projet312017\\Urbase2\\Urbase2\\src\\Urbase\\LOT_Pris.jrxml";
            JasperReport  jasperReport ;
            
          //  Map parametersMap = new HashMap();  
         //   parametersMap.put("test3",1);
            jasperReport = JasperCompileManager.compileReport(myreport);
            //System.out.println("rrrrrrr");
            db_connection db;
             db = new db_connection();
             String a ="";
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,null ,db.connection );
            //  System.out.println("sssss");
            
            
            
            
            JasperViewer.viewReport(jasperPrint,false);
         //   int DISPOSE_ON_CLOSE1 = JasperViewer.DISPOSE_ON_CLOSE
                 
            
        } catch (JRException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            System.out.println("thaankyou");
        }         // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12MouseClicked

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
 try {    
         
            String myreport = "C:\\Users\\Amine\\Desktop\\projet2\\Projet312017\\Urbase2\\Urbase2\\src\\Urbase\\Chart_Invst.jrxml";
            JasperReport  jasperReport ;
            
          //  Map parametersMap = new HashMap();  
         //   parametersMap.put("test3",1);
            jasperReport = JasperCompileManager.compileReport(myreport);
            //System.out.println("rrrrrrr");
            db_connection db;
             db = new db_connection();
             String a ="";
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,null ,db.connection );
            //  System.out.println("sssss");
            
            
            
            
            JasperViewer.viewReport(jasperPrint,false);
         //   int DISPOSE_ON_CLOSE1 = JasperViewer.DISPOSE_ON_CLOSE
                 
            
        } catch (JRException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            System.out.println("thaankyou");
        }         // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed

        // TODO add your handling code here:
        try {    
         
            String myreport = "C:\\Users\\Amine\\Desktop\\projet2\\Projet312017\\Urbase2\\Urbase2\\src\\Urbase\\Zone.jrxml";
            JasperReport  jasperReport ;
            
          //  Map parametersMap = new HashMap();  
         //   parametersMap.put("test3",1);
            jasperReport = JasperCompileManager.compileReport(myreport);
            //System.out.println("rrrrrrr");
            db_connection db;
             db = new db_connection();
             String a ="";
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,null ,db.connection );
            //  System.out.println("sssss");
            
            
            
            
            JasperViewer.viewReport(jasperPrint,false);
         //   int DISPOSE_ON_CLOSE1 = JasperViewer.DISPOSE_ON_CLOSE
                 
            
        } catch (JRException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            System.out.println("thaankyou");
        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
 try {    
         
            String myreport = "C:\\Users\\Service info\\Desktop\\Projet312017\\Urbase2\\Urbase2\\src\\edition\\report1.jrxml";
            JasperReport  jasperReport ;
            
          //  Map parametersMap = new HashMap();  
         //   parametersMap.put("test3",1);
            jasperReport = JasperCompileManager.compileReport(myreport);
            //System.out.println("rrrrrrr");
            db_connection db;
             db = new db_connection();
             String a ="";
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,null ,db.connection );
            //  System.out.println("sssss");
            
            
            
            
            JasperViewer.viewReport(jasperPrint,false);
         //   int DISPOSE_ON_CLOSE1 = JasperViewer.DISPOSE_ON_CLOSE
                 
            
        } catch (JRException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            System.out.println("thaankyou");
        }         // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu14MouseClicked
   Home2 x = new Home2();
x.setVisible(true);// TODO add your handling code here:     // TODO add your handling code here:
    }//GEN-LAST:event_jMenu14MouseClicked

    private void jMenu14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu14ActionPerformed

    }//GEN-LAST:event_jMenu14ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
Urbase x= new Urbase();
        x.setVisible(true);// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    pri