/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Urbase;

import DB.ResultSetTableModel;
import DB.db_connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author admin
 */
public class Urbase extends javax.swing.JFrame {

    /**
     * Creates new form Urbase
     */
ResultSet rs;
    db_connection db;
    DefaultTableModel model;
     DefaultTableModel model1;
     String id;
    static public int kk=1;
    public Urbase() {
        db = new db_connection();
        initComponents();
        table();
actualiser();
       
    }

    public void table() {
         
  
    
    try {
        rs = db.exécutionQuery("select * from tt");
        String name;
        
        model=new DefaultTableModel();
        model1=new DefaultTableModel();
        
        model.addColumn("wilaya");
        model.addColumn("zone");
        model.addColumn("investisseur");
        model.addColumn("lot");
        
        model1.addColumn("id_zi");
        model1.addColumn("id_invst");
        model1.addColumn("id_lot");
        
        
        while(rs.next()){
            model.addRow(new Object[]{rs.getString("lib_w"),rs.getString("lib_zi"),rs.getString("nom_invst"),rs.getString("lib_lot")});
            model1.addRow(new Object[]{rs.getString("id_zi"),rs.getString("id_invst"),rs.getString("id_lot")});
        }
        //    String  xx;
        
    //    xx= String.valueOf(model1.getValueAt(0,0));
        tbl_prod.setModel(model);
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbl_prod.getModel());
        tbl_prod.setRowSorter(sorter);
    } catch (SQLException ex) {
        Logger.getLogger(Urbase.class.getName()).log(Level.SEVERE, null, ex);
    }
 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_prod = new javax.swing.JTable();
        combo_wilaya = new javax.swing.JComboBox<>();
        combo_zone = new javax.swing.JComboBox<>();
        combo_invst = new javax.swing.JComboBox<>();
        combo_lot = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtrech = new javax.swing.JTextField();
        comrech = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tbl_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_prod);

        combo_wilaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_wilayaActionPerformed(evt);
            }
        });

        combo_zone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_zoneActionPerformed(evt);
            }
        });

        combo_invst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_invstActionPerformed(evt);
            }
        });

        combo_lot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_lotActionPerformed(evt);
            }
        });

        jLabel1.setText("Wilaya");

        jLabel2.setText("Zone_Indistriel");

        jLabel3.setText("Lot");

        jLabel4.setText("Investisseur");

        jButton1.setText("chercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("recherche par :");

        txtrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechActionPerformed(evt);
            }
        });

        comrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "wilaya", "zone", "lot", "investisseur" }));

        jButton3.setText("ajouter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Actualiser");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jMenu7.setText("Wilaya");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Zone");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu2.setText("Lot");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu6.setText("investisseur");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_zone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_wilaya, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_invst, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_lot, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 236, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(comrech, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtrech, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_wilaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_invst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_zone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_lot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comrech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtrech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("Urbase.Urbase.formWindowClosed()");        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        Wilaya k = null;
        try {
            k = new Wilaya();
        } catch (SQLException ex) {
            Logger.getLogger(Urbase.class.getName()).log(Level.SEVERE, null, ex);
        }
        k.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        Zone_Indst k = null;
        try {
            k = new Zone_Indst();
        } catch (SQLException ex) {
            Logger.getLogger(Urbase.class.getName()).log(Level.SEVERE, null, ex);
        }
        k.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        try {
            Lot k = new Lot();
            k.setVisible(true);        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Urbase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        Invst k = null;
        try {
            k = new Invst();
        } catch (SQLException ex) {
            Logger.getLogger(Urbase.class.getName()).log(Level.SEVERE, null, ex);
        }
        k.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MouseClicked

    private void combo_zoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_zoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_zoneActionPerformed

    private void combo_invstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_invstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_invstActionPerformed

    private void combo_lotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_lotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_lotActionPerformed

    private void txtrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        String lib_lot, x,wilaya;
        x = (String) combo_invst.getSelectedItem();
        lib_lot = (String) combo_lot.getSelectedItem();
wilaya = (String) combo_wilaya.getSelectedItem();
        rs = db.exécutionQuery("select id_invst from investisseur where nom_invst = '" + x + "'");
        String id_invst = null;
        try {
            while (rs.next()) {
                id_invst = rs.getString("id_invst");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Urbase.class.getName()).log(Level.SEVERE, null, ex);
        }

        int id_invs = Integer.parseInt(id_invst);
//////////////////////////////////////////////////////////////////////
 rs = db.exécutionQuery("select id_w from wilya where lib_w = '" + wilaya + "'");
        String id_wilaya = null;
        try {
            while (rs.next()) {
                id_wilaya = rs.getString("id_w");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Urbase.class.getName()).log(Level.SEVERE, null, ex);
        }

        int id_wilayai = Integer.parseInt(id_wilaya);
         String x1, x2;
  x2 = (String) combo_zone.getSelectedItem();
       rs = db.exécutionUpdate("update  zone_ind  set id_w='" + id_wilayai + "' where lib_zi='" + x2 + "'");
        //////////////////////////////////////id_zi//////////////////////////////////////////////////////////////////
       
        x1 = (String) combo_lot.getSelectedItem();
       
        //System.out.println("combo_invst x == " +x);
       rs = db.exécutionQuery("select id_zi from zone_ind where lib_zi = '" + x2 + "'");
        String id_zi = null;
        try {
            while (rs.next()) {
                id_zi = rs.getString("id_zi");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Urbase.class.getName()).log(Level.SEVERE, null, ex);
        }

        int id_zii = Integer.parseInt(id_zi);

        rs = db.exécutionUpdate("update  lot  set id_zi='" + id_zii + "',id_invst='" + id_invst + "'  where lib_lot='" + x1 + "'");
        ////////////////////////////////////////////////////////////////////zone///////////////////////////////////////
      //  rs = db.exécutionUpdate("update  zone_ind  set id_wi='" + id_zii + "' where lib_zi='" + x2 + "'");
        ///////////////////////////////////////////////////////////////////////////////////////////////////////
        rs = db.exécutionQuery("select * from tt");

        //tbl_prod.setModel(new ResultSetTableModel(rs));
table();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbl_prod.getModel());
        tbl_prod.setRowSorter(sorter);
        
//table();//afficher et actualiser le tableau
   actualiser();     
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
void actualiser(){
    
    
     String name_invst, name_wilaya, name_zone, name_lot;
        Date date;
        ResultSet[] rs1 = new ResultSet[4];
        rs1[0] = db.exécutionQuery("SELECT * FROM lot WHERE id_invst IS null");
        rs1[1] = db.exécutionQuery("SELECT * FROM wilya");
        rs1[2] = db.exécutionQuery("SELECT * FROM zone_ind");
        rs1[3] = db.exécutionQuery("SELECT * FROM investisseur");

//  ResultSet rs1= new ResultSet[3] ;
combo_invst.removeAllItems();
combo_lot.removeAllItems();
        combo_wilaya.removeAllItems();
        combo_zone.removeAllItems();
        
        try {
            while (rs1[0].next()) {
                name_lot = rs1[0].getString("lib_lot");
                combo_lot.addItem(name_lot);
            }
            while (rs1[1].next()) {
                name_wilaya = rs1[1].getString("lib_w");
                combo_wilaya.addItem(name_wilaya);

            }
            while (rs1[2].next()) {
                name_zone = rs1[2].getString("lib_zi");
                combo_zone.addItem(name_zone);
            }
            while (rs1[3].next()) {
                name_invst = rs1[3].getString("nom_invst");
                combo_invst.addItem(name_invst);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Urbase.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 
String h="";
int a,c;
//c= null;
 rs = db.exécutionUpdate("update lot set id_zi=null,id_invst=null where id_lot='"+id+"'");
table(); 
actualiser();
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ResultSet rs2;
         DefaultTableModel model3;
         
        
        
        
        if (txtrech.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        } else {
            if (comrech.getSelectedItem().equals("investisseur")) {
                rs2 = db.exécutionQuery("select lib_w as 'EEg',lib_zi,nom_invst,lib_lot from tt where nom_invst LIKE '" + txtrech.getText() + "%'");
                  tbl_prod.setModel(new ResultSetTableModel(rs2));
          
            } else if (comrech.getSelectedItem().equals("lot")) {
                rs2 = db.exécutionQuery("select lib_w ,lib_zi,nom_invst,lib_lot from tt where lib_lot LIKE '" + txtrech.getText() + "%'");
                tbl_prod.setModel(new ResultSetTableModel(rs2));

            }else if (comrech.getSelectedItem().equals("zone")) {
                rs2 = db.exécutionQuery("select lib_w as 'EEg',lib_zi,nom_invst,lib_lot from tt where lib_zi LIKE '" + txtrech.getText() + "%'");
                tbl_prod.setModel(new ResultSetTableModel(rs2));

            }else if (comrech.getSelectedItem().equals("wilaya")) {
                rs2 = db.exécutionQuery("select lib_w as 'EEg',lib_zi,nom_invst,lib_lot from test where lib_w  LIKE '" + txtrech.getText() + "%'");
                tbl_prod.setModel(new ResultSetTableModel(rs2));

            }
            
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo_wilayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_wilayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_wilayaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        rs = db.exécutionQuery("select * from test");

        tbl_prod.setModel(new ResultSetTableModel(rs));

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbl_prod.getModel());
        tbl_prod.setRowSorter(sorter);        // TODO add your handling code here:
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
       
        
        
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tbl_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_prodMouseClicked

id= String.valueOf(model1.getValueAt(tbl_prod.getSelectedRow(), 2));
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_prodMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urbase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urbase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urbase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urbase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urbase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_invst;
    private javax.swing.JComboBox<String> combo_lot;
    private javax.swing.JComboBox<String> combo_wilaya;
    private javax.swing.JComboBox<String> combo_zone;
    private javax.swing.JComboBox<String> comrech;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_prod;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables
}
